### PR TITLE
DOC: Cartopy v0.20 documentation

### PR DESCRIPTION
**Pull request by greglucas**
Docs downloaded from the CircleCI build.
https://circleci.com/docs/2.0/artifacts/#downloading-all-artifacts-for-a-build-on-circleci

```bash
curl -H "Circle-Token: $CIRCLE_TOKEN" https://circleci.com/api/v1.1/project/github/SciTools/cartopy/2856/artifacts \
   | grep -o 'https://[^"]*' \
   | wget -x -nH --verbose --header "Circle-Token: $CIRCLE_TOKEN" --input-file -
```

Followed the instructions in the base repo and removed the `.build_info` file included in the download.

### CODE REVIEW

**Comment by greglucas** [comment]
ping @SciTools/developers, I don't have commit rights on this repository.

**Comment by rcomer** [comment]
I don’t know anything about how this is generated, but it looks like the wrong release number has snuck in somehow.  See e.g. the [top of the API page](https://scitools.org.uk/cartopy/docs/latest/reference/index.html).

New docs looking good though - nice and clean.

**Comment by QuLogic** [comment]
Ah, this was wrong for 0.19.0 too, I think. @greglucas you should have pulled from the CircleCI build for the tag, _but_ it seems we  have excluded builds for tags.

**Comment by QuLogic** [comment]
I pushed a `v0.20.x` branch based on the tag, which maybe will trick CircleCI into a build without getting the version number wrong.

**Comment by greglucas** [comment]
@rcomer, looks like the new version worked: https://scitools.org.uk/cartopy/docs/latest/reference/index.html

Let us know if you find anything else missing/wrong!

**Pull request merged**
