### PR TITLE
Update copyright year

### PR DESCRIPTION
**Pull request by dkillick**
Update the copyright year in the template file. Build has been run to transmit the template changes to the built html files.

### CODE REVIEW

**Comment by dkillick** [comment]
ping @bjlittle

**Comment by ajdawson** [comment]
Just out of interest, how was this already correct on the tools page?

**Comment by bjlittle** [comment]
@dkillick What about the `README.md`?

**Comment by dkillick** [comment]
@ajdawson order that I made the changes to #141 and this in locally...

@bjlittle good spot! I'll change that one too.

**Comment by ajdawson** [comment]
OK fair enough, I just wanted to check that there isn't some way we can introduce inconsistency in error, seems not 👍

**Comment by dkillick** [comment]
@ajdawson thanks for checking - note I just edited my previous comment too

**Comment by dkillick** [comment]
Copyright updated in the README as well.

**Pull request merged**
