### PR TITLE
Added a scitools logo (a pretty rudimentary one).

### PR DESCRIPTION
**Pull request by pelson**

### CODE REVIEW

**Comment by ajdawson** [comment]
Looks a lot like the qi logo to me! At least from a moderate distance...

**Comment by pelson** [comment]
Hehe. I did double check that, as I had the same thought. I have absolutely no problem throwing this out, but would like to find a logo that encapsulates SciTools at some point 😄

**Comment by ajdawson** [comment]
I have no problem with it, just my first thought. Does the logo actually display anywhere with this change?

**Comment by pelson** [comment]
No. I would set it on github.com/scitools (instead of the random square blocks that github does), and then probably start rolling it out to thinks like the scitools.org.uk site where appropriate.

**Comment by pelson** [comment]
@scitools any comments on this as a straw-man for the SciTools logo?

**Comment by pelson** [comment]
Given the lack of complaints, I'm going to merge and move forwards. If anybody has a better alternative I'd be more than happy to review.

Note for historical purposes, the current "SciTools logo" is:

screen shot 2018-01-11 at 06 29 26

**Comment by pelson** [comment]
screen shot 2018-01-11 at 06 35 09


🎉

**Pull request merged**
